### ISSUE TITLE
Getting deprecation warning with grpc 

### ISSUE THREAD

**Issue by itaydr** [googleapis/nodejs-vision#120]
Getting an error when running on cloud functions. 
The error is: "(node:2) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead"

#### Environment details

  - OS:
  - Node.js version: google cloud functions (I guess it's node 6).
  - npm version: using 6.1.0 locally. Not sure if cloud functions reinstall the packages when I deploy.
  - `@google-cloud/vision` version: 0.20

#### Steps to reproduce

Using the package in cloud functions.

**Comment by JustinBeckwith** [comment]
@kinwa91 if I had to guess, this is probably coming from gax.  I think @kjin landed a PR to fix the issue, and we may just need to ship a build.

**Comment by fvilers** [comment]
Hi there, any ETA for a new build with this issue fixed?

**Comment by itaydressler** [comment]
Still getting this issue. 
Tried updating to the node 8 environment on google cloud, and using the v0.21 nodejs-vision package.

**Comment by Ben5tone** [comment]
I'm also having the same issue while tring to use API's documentation example with nodejs 8. I have installed gax 19 but i'm still obtaining the same result.

**Comment by TrustyTechSG** [comment]
I have the same problems running it on Cloud Functions, keep receiving this error log.

**Comment by JustinBeckwith** [comment]
Greetings folks!  We can confirm this is an issue, and we're actively working on a fix :)

**Comment by alexander-fenster** [comment]
This is being taken care of in https://github.com/googleapis/gax-nodejs/issues/286. I will update this issue when the new gax version is available.

**Comment by ggprod** [comment]
@alexander-fenster  Looking at https://github.com/googleapis/gax-nodejs/issues/286 it looks like the new gax version is available?

**Comment by alexander-fenster** [comment]
@ggprod unfortunately the change that was merged to master does not work with long running operations (I have reopened that issue to make it clear). I'm going to revert half of the changes that will still avoid using the deprecated `grpc.load`. ETA for the release is 1-2 days from now. Thanks!

**Comment by JustinBeckwith** [comment]
This should be fixed in the latest release 🎉

**Comment by pojoba02** [comment]
@JustinBeckwith this issue is not resolved, am encountering this problem in my cloud function, any solution?

**Comment by JustinBeckwith** [comment]
Are you using the latest version of the module? 0.24.0?

**Comment by pojoba02** [comment]
am using 0.25.0

**Comment by pojoba02** [comment]
@JustinBeckwith i was able to update it locally to 0.24.0 is working now, 
with 0.25.0, was referring to grpc doe.

**Comment by DSanghera** [comment]
Hi there, I'm still getting this error. Could someone help out with steps on how to fix? Thx!
